### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by vasily-kirichenko** [ManoMarks/docker-swarm-visualizer#19]
![image](https://cloud.githubusercontent.com/assets/873919/18043093/34edb270-6dce-11e6-9f90-f057ed7f33c5.png)

```
$ docker logs bb9
npm info it worked if it ends with ok
npm info using npm@2.14.4
npm info using node@v4.1.2
npm info prestart swarmVisualizer@0.0.1
npm info start swarmVisualizer@0.0.1

> swarmVisualizer@0.0.1 start /app
> node server.js

undefined
```

**Comment by briandoodyie** [comment]
what version of docker are you using? I see this error when i am using Docker Engine 1.11 ->https://github.com/ManoMarks/docker-swarm-visualizer/issues/12

**Comment by rickpeters** [comment]
I had the same problem. Since there is almost no logging it was difficult to determine where to start. When I looked in the browser code I saw that the `HOST` entry is used 'locally' in the browser. Meaning it should be able to resolve. In my case that meant using a FQDN. Furthermore after I changed the port to 5000 it worked (even though port 8080 was still available for me).

I did something like this:
```
docker run -it -d -p 5000:5000 --name=visualizer -e PORT=5000 -e HOST=sou692.so.kadaster.nl -v /var/run/docker.sock:/var/run/docker.sock manomarks/visualizer
```

and now it works like a charm :-)

**Comment by megastef** [comment]
For me it did work after using the public IP in HOST on a digital ocean droplet. It did not work with ```-e HOST=$(hostname)``` on the master node.

**Comment by vasily-kirichenko** [comment]
@rickpeters It's helped. Thanks!

**Comment by vikasksrivastava** [comment]
I had the same issue , fixed by disabling selinux .
