### ISSUE TITLE
Errors on service creation

### ISSUE THREAD

**Issue by shuntera** [ManoMarks/docker-swarm-visualizer#63]
When I created a Docker swarm service with the following (I had created the image visualizer-arm locally):

docker service create \
  --name=viz \
  --publish=8080:8080/tcp \
  --constraint=node.role==manager \
  --mount=type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
  visualizer-arm

I got these errors:
unable to pin image visualizer-arm to digest: errors:
denied: requested access to the resource is denied
unauthorized: authentication required

And when I tried to scale it up I found that all the services were running on the swarm controller and not on the worker nodes.

Another service I have is running on the worker nodes without an issue.

**Comment by ManoMarks** [comment]
@alexellis can you check on this?

**Comment by alexellis** [comment]
This is a standard Docker error message when images are local rather than in the hub or a local registry. Here's an issue for more background​ https://github.com/docker/docker/issues/29205

**Comment by ManoMarks** [comment]
Ah. Thanks @alexellis, I just saw "arm" and sent it to you :-). 
As for everything running on the manager, that's as expected. You have:
--constraint=node.role==manager as part of the command. The visualizer needs to run on a manager, otherwise it can't populate the data.
I'm closing this issue assuming your questions have been answered.
